version: '3'
services:
  gradimio:
    build:
      #network: host
      dockerfile: "Dockerfile"
      context: .
    ports:
      - "7860:7860"
    volumes:
      - .:/gradimio
    working_dir: /gradimio
    command: ["python3", "main.py"]
