version: '3'
services:
  gradimio:
    build:
      network: host
      dockerfile: "Dockerfile"
      context: .
    ports:
      - "7860:7860"
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["python3", "main.py"]